### ISSUE TITLE
Opt-in support for custom objects?

### ISSUE THREAD

**Issue by colinta** [OTGApps/motion_print#9]
I was looking at the CDQ additions, and thought: now there's a long and slippery slope, adding support for other gems, one class at a time... tons of work, opinionated, and people who write smaller (less popular) gems would be less likely to have their PRs merged.  Or, since Mark is egalitarian about these things, the motion_print source fills with all the pretty-printers of every little gem out there.

There's got to be a better way.

gems could opt-in to supporting motion_print. I think a simple `respond_to?(:motion_print)` would do it, and it's very unlikely that anyone declared a method called `motion_print` already (citation: [search for 'def motion_print'](https://github.com/search?q=def+motion_print&type=Code&utf8=✓) and compare with [a search for 'def to_s'](https://github.com/search?q=def+motion_print&type=Code&utf8=✓)).

###### cdq_managed_object_mp.rb
```ruby
class CDQManagedObject

  def motion_print(mp, indent_level = 1)
    # Requires CDQ > v0.1.10
    if respond_to? :attributes
      "OID: " + mp.colorize(oid.gsub('"','')) + "\n" + mp.l_hash(attributes, indent_level)
    else
      # old colorless method, still more informative than nothing
      mp.colorize(log)
    end
  end

end
```

Interested?

**Comment by jamonholmgren** [comment]
I really like the idea of a `motion_print` method. I'd be happy to build that into ProMotion.

**Comment by colinta** [comment]
Hey @markrickert any thoughts?  We can close if this is "out of scope".  Though, I'm still a fan.

**Comment by markrickert** [comment]
Hey @colinta... sorry that this completely slipped my notice. I like this idea and I think it's a great step to removing any code related to other gems from the library. Wondering what @GantMan thinks?

**Comment by GantMan** [comment]
So if I'm reading this right, we'd be adding some kind of decorator pattern.

Ideally any gem would add a custom object giving itself  a motion_printed detail.  MotionPrint would first check if the object has a cutom decorator and if so it uses it.  So presentation of objects reside in those objects/gems, but not motion_print.  If no decorator exists, motion_print will just do a coloration as a vanilla object.

@colinta hit the nail on the head with the problem being that we don't want to inflate `mp` with lesser known gems.  My concern would be that we now need gem creators to be on board to implement their own `mp`.   Not that it isn't something @markrickert  couldn't knock out in one evening of his pull-request tirades.   I just would hope all gem creators would be into it.

**Comment by markrickert** [comment]
Or we could have another gem... something like `motion_print_additions` where we simply reopen a bunch of known gem classes and add our own decorators.

**Comment by colinta** [comment]
@markrickert That could work, though it's almost as easy to open a PR per-project, there would not be many projects that would refuse to support motion_print.

I wonder if there's a way to check for the existence of a gem, so during `setup`, you could include the motion_print support files only *if* motion_print is an included Gem.  `if defined?(MotionPrint::Version)`, something like that.

**Comment by GantMan** [comment]
I like where this is going.   I'm down for either solution.

**Comment by colinta** [comment]
Ready for a PR?  Changes to my proposed solution (<https://github.com/colinta/motion_print/commit/b4d8173>)

**Comment by markrickert** [comment]
yup! send'er on over!

**Comment by colinta** [comment]
Sent #13
